// This file is autogenerated by lib/feature-plugin.js

import mozjpegEncode from "../../lib/encoders/mozJPEG/worker/mozjpegEncode";
import resize from "../../lib/processors/resize/worker/resize";


export const methodNames = [
  "mozjpegEncode",
  "resize"
] as const;

export interface BridgeMethods {
  mozjpegEncode(
    ...args: Parameters<typeof mozjpegEncode>
  ): Promise<ReturnType<typeof mozjpegEncode>>;
  resize(
    ...args: Parameters<typeof resize>
  ): Promise<ReturnType<typeof resize>>;
}